use_frameworks!

source 'https://cdn.cocoapods.org/'
source 'https://github.com/n26/flowkit-ios'

platform :ios, '12.0'

target 'flowkitAdditions_Example' do
  pod 'flowkitAdditions', :path => '../../'
  
  target 'flowkitAdditions_Tests' do
    pod 'flowkit-ios', :testspecs => ['Tests']
  end
end
