use_frameworks!

platform :ios, '13.0'

pod 'Shared', :path => './Shared'

target 'flowkitSwiftUI' do
  pod 'flowkit-ios/Additions', :path => '../../'
end

target 'flowkitUIKit' do
  pod 'flowkit-ios/Additions', :path => '../../'
end